### ISSUE TITLE
why the type is 0x0004

### ISSUE THREAD

**Issue by someonebw** [Jamesits/linux-gre-keepalive#3]

**Comment by someonebw** [comment]
I'm on the B-server, via TCpreplay, sending it regularly

I built the keepalive package myself and it was successful.

The firewall thinks end B is alive

[keepalive-cap-in-B-server.zip](https://github.com/Jamesits/linux-gre-keepalive/files/9062416/keepalive-cap-in-B-server.zip)

**Comment by Jamesits** [comment]
I think Huawei implemented a slightly different packet format for sending GRE replies. 

This one is a normal, Cisco-compatible GRE keepalive packet, with outer GRE protocol 0x0800 (IPv4). 
![image](https://user-images.githubusercontent.com/1297257/177892509-501829cc-5aae-4880-b837-9a02a2b7e5ca.png)

This one is a GRE packet with outer GRE protocol 0x0004 (unassigned), so Wireshark cannot decode it. But if you watch close enough, you might discover that the data segment is still an IPv4 packet (src=36.26.87.125, dst=111.47.24.27, proto=0x2f/GRE). I've underlined the IP addresses on the picture.
![image](https://user-images.githubusercontent.com/1297257/177892932-b278a7c8-5a0e-4e62-b24e-8cfa629f57cd.png)

My guess is that Huawei is trying to probe what kind of a device is at the opposite of the tunnel. Unfortunately I don't have any Huawei routers in my lab and I cannot find any documentation on the internet about this behavior. If you want to further experiment on this packet type, you can patch this line:

https://github.com/Jamesits/linux-gre-keepalive/blob/702969c099c86a740a5c2c058446455896bd402a/src/keepalive_gre.c#L81=

add a `|| outer_grehdr -> proto == bpf_htons(0x0004)` match condition here.

**Comment by someonebw** [comment]
Thank you for your reply, Jamesits

I modified the source code as you suggested.

They tested it again.

But there is still a problem, it seems to be the same as before, right?

Now I have two questions.

1. If I don't comment this out.

# # # # # # # # # # # # # # # # #
			inner_grehdr -> proto != 0
//			|| inner_iphdr -> saddr != outer_iphdr -> daddr
//			|| inner_iphdr -> daddr != outer_iphdr -> saddr
			) goto out;

# # # # # # # # # # # # # # # # #

There doesn't seem to be a Keepalive packet that sends a response.

2. I have modified the judgment of line L81 according to your suggestion, but the package sent is the same as before?
![图片](https://user-images.githubusercontent.com/8149858/177901375-fbebc7ee-9ff8-4716-8350-c4a9645030a0.png)

![图片](https://user-images.githubusercontent.com/8149858/177901432-b2914469-862d-4484-a62f-d7d8ff004199.png)

I'm a little confused.

Where did I change that? Is that a problem?
########################################################################################
In hexdump, it's supposed to be
00, 00, 08, 00.
Why is it time to respond
Turned out to be
00 00 00 04

????,some ebpf's bug? None of the relevant HEX bytes were found in the a2B package.

 


![图片](https://user-images.githubusercontent.com/8149858/177901778-1d4786b7-a557-4a6a-9c6f-2509c19d5556.png)

[packetCaptureList(11).zip](https://github.com/Jamesits/linux-gre-keepalive/files/9068329/packetCaptureList.11.zip)

**Comment by someonebw** [comment]
I found that type 0x0004 also appeared in issues before.
#
https://github.com/Jamesits/linux-gre-keepalive/issues/1

![图片](https://user-images.githubusercontent.com/8149858/177905950-665eca0f-50e7-4239-8c24-15aeb8c10c14.png)

**Comment by someonebw** [comment]
Jamesits, I find the problem now is in this type of place.
I modified the hex related field of the packet sent by end B and found that

Keepalive_gre.o
Outgoing package, that's where this type is wrong? why
Should have been
00 00 08 00 
It became
00 00 00 04
I will experiment with the relevant package and make a summary for you.
![图片](https://user-images.githubusercontent.com/8149858/178115128-10bce5bd-31a1-46b9-b4c8-7ff45d18bff2.png)

##
By the way when i change some route for eth2 (iproute2)
so i can pcap Keepalive_gre.o send's packet in B server by tcpdump!

[pcap-eth2-B.zip](https://github.com/Jamesits/linux-gre-keepalive/files/9077549/pcap-eth2-B.zip)

![图片](https://user-images.githubusercontent.com/8149858/178115407-71978aa5-c210-4878-9ef3-30a8998c7628.png)



###################all file in ALL-FILE.zip
1#huawei fw send keepalive packet
A-FW-huawei-send.pcap


2#keepalive_gre.o send packet to hexdump
B-Linux-send（hexdump）.txt


3#keepalive_gre.o send packet to hexdump ;edit the 0x0004 to 0x0080
B-Linux-send（hexdump）-edited.txt

4#B-Linux-send（hexdump）-edited.txt (hexdump file to pcap)
B-Linux-send（hexdump）-edited.pcap

5#keepalive_gre.o send packet (type is 0x0004)
B-Linux-send（keepalive_gre.o）.pcap

6#my custom's keepalive packet (is ok to fw-hw)
keepalive-ok-a2b（hw-fw）-b2a（my-build）.pcap

Finally, I found that the 4# packet and my customized packet(6#) are the same.



[ALL-FILE.zip](https://github.com/Jamesits/linux-gre-keepalive/files/9077532/ALL-FILE.zip)

**Comment by Jamesits** [comment]
Yes, I think your conclusion is correct. 

BTW, what's your kernel version? It might be related to a kernel bug.

**Comment by someonebw** [comment]
#centos 8.2
[root@ecs-gre-xw ~]# uname -ar
Linux ecs-gre-xw 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@ecs-gre-xw ~]# cat /etc/redhat-release 
CentOS Stream release 8

BTW, There is no problem on your side of the core version, how much use; Can you tell me so I can test the new version and see if there's a core problem?

**Comment by someonebw** [comment]
The problem may not be the core problem, I replaced the core of 5.10.4-1, the same problem reappears.

![图片](https://user-images.githubusercontent.com/8149858/178133183-412fd540-e4ba-4b2c-8626-52a00c040d12.png)

**Comment by someonebw** [comment]
pcap in 5.10.4-1 kernel （from B）
[B.zip](https://github.com/Jamesits/linux-gre-keepalive/files/9078532/B.zip)

**Comment by someonebw** [comment]
Jamesits，How to deal with this problem
If your lab does not have a Huawei router
I can cooperate with the test by configuring the GRE tunnel to your IP address on my Huawei device.
